### ISSUE TITLE
Emitter.Listener callback not compiles. Not works.

### ISSUE THREAD

**Issue by Hayko985** [sacOO7/socketcluster-client-java#28] opened 2018-04-13 13:20 UTC
Hi, I'm creating socket client part, and I have a problem in Emitter.Listener. The listener not throws any exception, it only not compiles. SO when I'm doing debug, and I set breakpoint in that callback, it jumps over the call. I have some pictures where I explain my problem very well. 
![screen shot 2018-04-13 at 4 17 52 pm](https://user-images.githubusercontent.com/30463912/38736952-bac7f732-3f3e-11e8-9cc6-9d197cbebf76.png)
![screen shot 2018-04-13 at 4 24 22 pm](https://user-images.githubusercontent.com/30463912/38736955-be5f88f6-3f3e-11e8-8371-1eb37d764f8d.png)
![screen shot 2018-04-13 at 4 24 53 pm](https://user-images.githubusercontent.com/30463912/38736957-bff121f2-3f3e-11e8-92b0-4f35cedad22c.png)
![screen shot 2018-04-13 at 4 53 07 pm](https://user-images.githubusercontent.com/30463912/38736959-c1ae61b2-3f3e-11e8-82fa-c24be530f510.png)
![screen shot 2018-04-13 at 4 53 22 pm](https://user-images.githubusercontent.com/30463912/38736964-c3334674-3f3e-11e8-9009-1d25f96134c1.png)
Any ideas why it's not working. It connects well, and the state is OPEN, but in that call I have  to send my tokens into server.

**Comment by Hayko985** [comment] 2018-04-13 15:49
From server they said that they have an exception like this SocketProtocolError: Client pong timed out. I have no problem with access and refresh tokens. And the internet connection is great, if I have an internet connection problem, I can't to connect. But I'm connecting successful. 

Yes and one more thing too. I moved the socket.connect() method after the listener and socket.on(), and now in debug mode it not gives exception like "socket = no such instance field: 'val$socket' ".

**Comment by sacOO7** [comment] 2018-04-13 16:16
Sure, I will take a look at it @hyko

**Comment by Hayko985** [comment] 2018-04-13 17:44
Thank you very much, please help me if you can)) @sacOO7

**Comment by Hayko985** [comment] 2018-04-15 11:12
@sacOO7  Hi)) How are you? Please can you help me to fix this problem, tomorrow is the last day, and if i can't do this, they will not bring me to work. So please, help me if you can)) Thank you.

**Comment by Hayko985** [comment] 2018-04-15 11:14
@sacOO7  Here is my vk, you can connect with me)) https://vk.com/id192526595

**Comment by sacOO7** [comment] 2018-04-15 13:41
Hi @hyko, sorry for late reply. Little busy those days. Will get back to
you for sure (today night ...., Probably after 2-3 hours)

**Comment by Hayko985** [comment] 2018-04-15 18:35
@sacOO7  hey bro) I think you can't help me today. If you can't, then can you help me tomorrow, but soon? And how can I connect with you? Any vk, whatsapp or something else.

**Comment by sacOO7** [comment] 2018-04-15 19:01
Hi @Hayko985, Can you explain for which event are you exactly trying to listening to?

**Comment by sacOO7** [comment] 2018-04-15 19:01
Sending auth data is not supposed to be inside listener

**Comment by sacOO7** [comment] 2018-04-15 19:02
Instead before connecting call socket.setAuthToken("Your JWT token here")

**Comment by sacOO7** [comment] 2018-04-15 19:03
You can see that method here https://github.com/sacOO7/socketcluster-client-java/blob/master/src/main/java/io/github/sac/Socket.java#L90

**Comment by sacOO7** [comment] 2018-04-15 19:08
Please post here context of your problem as well as little server code that sends data so that I can understand exact problem

**Comment by Hayko985** [comment] 2018-04-15 19:11
Ok, so when I'm giving my jsonobject to that data, instead I need to use setAuthToken. I'm listening to connect event. I'm beginner yet in sockets)) Server says that client not sends pong. What is this pong and how to send it?

**Comment by Hayko985** [comment] 2018-04-16 07:32
@sacOO7 Hi) How are you? I done socket.setAuthToken("Your JWT token here"), but that not helped. Server says that client not sends pong. So you know what is that pong and how to send it?

**Comment by sacOO7** [comment] 2018-04-16 07:40
Hi @Hayko, if you are not writing any server code, you don't need to set
auth token. You can check example working code here
https://github.com/sacOO7/socketcluster-client-java/blob/master/src/main/java/Main.java

**Comment by sacOO7** [comment] 2018-04-16 07:55
Generally auth token is set by server itself, you will receive it and save
it.Then reuse it using set auth token method. You will receive token in
onsetAuthtoken callback, there you can save it and use it again.

**Comment by Hayko985** [comment] 2018-04-16 08:41
@sacOO7  I done as in this example and in logs it says "Authentication is required (optional)". So in socket.setlistener(new BasicListener{}) there is a method onSetAuthToken(). I need to give here my jwt?

**Comment by Hayko985** [comment] 2018-04-16 08:42
![screen shot 2018-04-16 at 12 41 40 pm](https://user-images.githubusercontent.com/30463912/38798788-9ef5b878-4173-11e8-94d1-755ba0dd5965.png)

**Comment by Hayko985** [comment] 2018-04-16 08:44
@sacOO7  I'm beginner in this sockets and sorry for disturbing you, but i need your help))

**Comment by sacOO7** [comment] 2018-04-16 12:47
Hi @Hayko985, I am not sure why you are sending auth event to server

**Comment by sacOO7** [comment] 2018-04-16 12:47
Can you put your server URL here?

**Comment by Hayko985** [comment] 2018-04-16 13:01
@sacOO7  Hi)) After long suffering I'm already sending my pong)) So in server there is no any pong exception. The only issue is now that I'm using oauth2 and I can't to send jwm, I need to send my oauth object, so my access token and refresh token. 

Let me show some of the server logs and you'll see the exceptions.

[Warning] AuthTokenInvalidError: jwt malformed
at emitOne (events.js:96:13)
    at Socket.emit (events.js:189:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
  name: 'error',
  length: 202,
  severity: 'ERROR',
  code: '42883',
  detail: undefined,
  hint: 'No operator matches the given name and argument type(s). You might need
 to add explicit type casts.',
  position: '497',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_oper.c',
  line: '728',
  routine: 'op_error' }
newuser info socket is   KCtCwozsPkSRE0AE
(node:12084) UnhandledPromiseRejectionWarning: Unhandled promise rejection (reje
ction id: 6): TypeError: Cannot read property '0' of undefined


So any idea bro? Yeah and thank you very much for that help.

**Comment by sacOO7** [comment] 2018-04-16 13:06
Can you give me the context of your server code? I am not sure how it is
working or supposed to work. Normally if you start school server, on normal
mode, you do not require to send JWT.

**Comment by Hayko985** [comment] 2018-04-16 13:19
I can only see the source code. Here the scrypt. 


<script type="text/javascript">
--
  |  
  |  
  |  
  | var accessToken = "";
  | var refreshToken = "";
  | var aaa = function () {
  | $.get("http://localhost:1986/api/token?grant_type=password&client_secret=5a98bc9cba96b3048255936dd&client_id=c27ca-943-55e42a6c&email=e7@kla.com&\n" +
  | "password=password", function (data) {
  | accessToken = data.accessToken;
  | refreshToken = data.refreshToken;
  | enter('u3');
  | // enter('mainChannel');
  | $('.test-area').text(JSON.stringify(data));
  | });
  | };
  | var bbb = function () {
  | $.get("http://localhost:1986/api/token?grant_type=password&client_secret=35828994c89f667e53baf&client_id=c59ce9-09-488d-731-b0e&" +
  | "email=e6&password=password", function (data) {
  | accessToken = data.accessToken;
  | refreshToken = data.refreshToken;
  | enter('u6');
  | // enter('mainChannel');
  | $('.test-area').text(JSON.stringify(data));
  | });
  | };
  |  
  | var ccc = function () {
  | $.get("http://localhost:1986/api/token?grant_type=password&client_secret=2a3b8922284caa56de5da4f02865da42b&client_id=c9f8-9d-4a9-9e-2c1297fa1&" +
  | "email=e7&password=password", function (data) {
  | accessToken = data.accessToken;
  | refreshToken = data.refreshToken;
  | enter('u7');
  | // enter('mainChannel');
  | $('.test-area').text(JSON.stringify(data));
  | });
  | };
  |  
  |  
  | var setRoom = function () {
  | RoomName = $('.inputRoom').val();
  | };
  |  
  | var sendMessage = function () {
  | let socket = socketCluster.connect();
  | let test = $('.message').val();
  | alert(test);
  | // socket.emit('chat message', {room: RoomName, msg: test, accessToken: accessToken});
  | socket.emit('begem',  {user: RoomName, msg: test});
  | // socket.emit('ping', 'This is a PING message')
  | // socket.publish('begem', {from: 'alice456', message: 'Hi Bob!'});
  | }
  | var enter = function (channelName) {
  | // Initiate the connection to the server
  | var socket = socketCluster.connect();
  |  
  | socket.on('error', function (err) {
  | throw 'Socket error - ' + err;
  | });
  |  
  | socket.on('connect', function () {
  | console.log('CONNECTED accessToken = ', accessToken);
  | console.log('CONNECTED refreshToken = ', refreshToken);
  | let  data = {};
  | data.accessToken = accessToken;
  | data.refreshToken =refreshToken;
  | socket.emit('auth', data);
  | // socket.emit('auth', accessToken, refreshToken);
  | });
  |  
  |  
  |  
  | // socket.on('updateUserList', function (data) {
  | //     console.log('updateUserList: ' + data);
  | // });
  | // socket.on('message', function (data) {
  | //     console.log('ya es inch lav messagea: ' + data);
  | // });
  |  
  |  
  | var mainChannel = socket.subscribe(channelName);
  |  
  | mainChannel.on('subscribeFail', function (err) {
  | console.log('Failed to subscribe to the sample channel due to error: ' + err);
  | });
  |  
  | mainChannel.watch(function (text) {
  | console.log('server info : ', text);
  | });
  |  
  | // console.log('running channel', channelName);
  | //     console.log('under socket', mainChannel);
  | //     var initChannel = function(channelName){
  | };
  | </script>

**Comment by sacOO7** [comment] 2018-04-16 13:51
I see

**Comment by sacOO7** [comment] 2018-04-16 13:58
Is this server code written by you? or is it a chatroom service... I just want to know if that code is working

**Comment by Hayko985** [comment] 2018-04-16 14:02
This is for chatroom)) Yes I have accessToken and refreshToken. But wait a while because they are doing work on server and now it's unavailable))

**Comment by sacOO7** [comment] 2018-04-16 14:03
Just a quick question... Are you able to connect to server. I believe you should receive connected to server in onconnect function callback.

**Comment by sacOO7** [comment] 2018-04-16 14:10
Just write down this code after sc.connectAsync method call.
```
JSONObject authObject = new JSONObject();
authObject.put("accessToken", "Your access token here");
authObject.put("refreshToken", "Your refresh token here");
sc.emit("auth", authObject);
```

**Comment by Hayko985** [comment] 2018-04-16 14:21
Yes of course. Yeah and I changed the connectAsync() to connect() and moved it into thread. So I don't know what's the difference between this two, because it's connects anyway.

**Comment by Hayko985** [comment] 2018-04-16 14:27
Here my code after adding the JsonObject part 

![screen shot 2018-04-16 at 6 26 37 pm](https://user-images.githubusercontent.com/30463912/38814932-c2faff32-41a3-11e8-91cd-601cb6bf8439.png)

**Comment by sacOO7** [comment] 2018-04-16 15:03
What is sc.on("connect"). You do not need it.

**Comment by Hayko985** [comment] 2018-04-16 15:05
@sacOO7  I saw it in server code, I thought I need it. Ok but what is that method means?

**Comment by sacOO7** [comment] 2018-04-16 15:05
To get whether you get connected or not, you need to register basic listener. I think, you probably need to take a look at documentation on repo( https://github.com/sacOO7/socketcluster-client-java). It will solve most of your problems :+1:

**Comment by Hayko985** [comment] 2018-04-16 15:11
Yeah I done already the basic listener, that not visible in picture))) 
![screen shot 2018-04-16 at 7 11 07 pm](https://user-images.githubusercontent.com/30463912/38817693-f92bd63e-41a9-11e8-8620-07fea43eae55.png)

**Comment by Hayko985** [comment] 2018-04-16 15:15
Oh I understood. So with socket.on() I can get message from server and with socket.emit() I can send data to server. I'll read the documentation today)) The server not works yet)))

**Comment by Hayko985** [comment] 2018-04-17 09:01
@sacOO7 Hi) How are you? So I done something like this as you said, but the server not gets my data, that I'm sending with emit. Watch here.
![screen shot 2018-04-17 at 1 00 00 pm](https://user-images.githubusercontent.com/30463912/38859617-77d72b2e-423f-11e8-940a-0bc42f815456.png)

**Comment by Hayko985** [comment] 2018-04-17 10:33
@sacOO7  Man there's another little problem, I don't know why is it working like this, but when I'm running my app, that not sends data to server, but when I'm doing debug, it sends the data successful, but when it sends there's an error too.

Here the error log.
error TypeError: Cannot read property 'username' of undefined
    at process._tickCallback (internal/process/next_tick.js:103:7)
newuser info socket is   08GaAmezm27PcvAD
(node:1416) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejec
tion id: 3): TypeError: Cannot read property '0' of undefined

**Comment by Hayko985** [comment] 2018-04-17 13:06
@sacOO7 Ok I'll wait you bro) Thanks a lot)))

**Comment by sacOO7** [comment] 2018-04-17 14:02
Hi @Hayko985 , the problem is because, you are trying to subscribe before handshake is made with server. I think should emit auth event inside onConnected callback. It should work.

**Comment by Hayko985** [comment] 2018-04-17 14:12
@sacOO7 Hi)) All works thanks. So one more question too. Is there any watch method in client part? 
![screen shot 2018-04-17 at 6 12 09 pm](https://user-images.githubusercontent.com/30463912/38875191-e70232c0-426a-11e8-96f4-5e0e6ae42ed8.png)

That's in server part. How can I do this in client part?

**Comment by sacOO7** [comment] 2018-04-17 18:48
Since problem is solved, I will close the issue ..

**Closed** 2018-04-17 18:48 UTC

**Comment by sacOO7** [comment] 2018-04-18 05:32
Btw @Hayko985, let me know if you want to suggest any improvement in the current client. Also, do **STAR** the client if you like it :).

**Comment by Hayko985** [comment] 2018-04-18 06:34
Yeah, I already gave a star)))))

**Comment by Hayko985** [comment] 2018-04-18 13:30
@sacOO7 Hi)) How are you? Can I give you a little question? How can I do this emit part in android. This code is in javascrypt, so I don't know how to give in android the roomName and the message text.

![screen shot 2018-04-18 at 5 30 28 pm](https://user-images.githubusercontent.com/30463912/38934986-3d21fd8e-432e-11e8-85c6-ee6e5ed4b3c2.png)

**Comment by Hayko985** [comment] 2018-04-18 15:12
I already solved thanks)))
